export default {
	theme: {
		files: [ 'src/*.css', 'src/js/*.js', 'src/**/*.php' ],
		build: [
			'src/**',
			'!**/.*',
			'!**/docs/**',
			'!**/tests/**',
			'!**/apigen/**',
			'!**/apigen.neon',
			'!**/*.scss',
			'!**/composer.*',
			'!**/license.txt',
			'!**/LICENSE.txt',
			'!**/*.yml',
			'!**/*.md',
			'!**/doc/**',
			'!**/Dockerfile',
			'!**/make.sh',
			'!**/lang/**',
			'!**/Gruntfile.js',
			'!**/gulpfile.js',
			'!**/Gulpfile.js',
			'!**/package*.json',
			'!**/phpunit*',
			'!**/README.md',
			'!**/CHANGELOG.md',
			'!**/CONTRIBUTING.md',
			'!**/LICENSE.md',
			'!**/LICENSE',
			'!**/phpcs*',
			'!src/assets/js/src/**',
			'!src/assets/svg/**',
			'!src/vendor/**/readme.txt',
			'!src/vendor/**/changelog.txt',
			'!src/vendor/tgmpa/tgm-plugin-activation/languages/**',
			'!src/vendor/tgmpa/tgm-plugin-activation/plugins/**',
			'!src/vendor/tgmpa/tgm-plugin-activation/example.php',
		],
	},
};
